#!/bin/sh

# use the pipenv command from within a docker container from shell on host

ARGS="$@"

docker-compose exec figstudios-dev-be-django-dev -c "cd /code/application && pipenv run pytest $ARGS"
